%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-urg-stamped
Version:        0.0.13
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS urg_stamped package

License:        Apache 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-roscpp
Requires:       ros-noetic-sensor-msgs
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-roscpp
BuildRequires:  ros-noetic-roslint
BuildRequires:  ros-noetic-rostest
BuildRequires:  ros-noetic-rosunit
BuildRequires:  ros-noetic-sensor-msgs
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Precisely stamped URG driver for ROS

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Fri Aug 06 2021 Atsushi Watanabe <atsushi.w@ieee.org> - 0.0.13-1
- Autogenerated by Bloom

* Sun Jul 11 2021 Atsushi Watanabe <atsushi.w@ieee.org> - 0.0.12-1
- Autogenerated by Bloom

* Fri Apr 23 2021 Atsushi Watanabe <atsushi.w@ieee.org> - 0.0.11-1
- Autogenerated by Bloom

* Thu Apr 08 2021 Atsushi Watanabe <atsushi.w@ieee.org> - 0.0.10-1
- Autogenerated by Bloom

* Wed Mar 10 2021 Atsushi Watanabe <atsushi.w@ieee.org> - 0.0.9-1
- Autogenerated by Bloom

* Wed Aug 12 2020 Atsushi Watanabe <atsushi.w@ieee.org> - 0.0.7-1
- Autogenerated by Bloom

* Wed Jun 24 2020 Atsushi Watanabe <atsushi.w@ieee.org> - 0.0.6-1
- Autogenerated by Bloom

* Tue Apr 07 2020 Atsushi Watanabe <atsushi.w@ieee.org> - 0.0.5-1
- Autogenerated by Bloom

